### ISSUE TITLE
Problem att starta applikationen

### ISSUE THREAD

**Issue by jh222vp** [fjohansson92/1DV450_fj222dr#1]
Hej

Har följt dina steg för att starta webbapplikationen men lyckas tyvärr inte starta den. Verkar få något fel med en fil som ligger under "tmp/pids/server.pid". 

"A Server is already running. Exiting..".
Försökt ta bort/tömma filen men hoppar tillbaka om och om igen vid start av ny server.

**Comment by fjohansson92** [comment]
Konstigt. Har du använt rails server som jag så du har lite koll? Provat
körat på annan port? Kopiera gärna hela felet.

Den 12 februari 2015 14:32 skrev jh222vp notifications@github.com:

**Comment by fjohansson92** [comment]
Har glömt att skriva att du måste göra en bundle install men det gjorde du
säkert.

Den 12 februari 2015 14:36 skrev Filip Johansson fj222dr@student.lnu.se:

**Comment by jh222vp** [comment]
Fick igång den nu. Behövde köra servern som production mode.

**Comment by jh222vp** [comment]
Japp

Den 12 februari 2015 14:48 skrev Jonas Holte jh222vp@student.lnu.se:

> Fick igång den nu. Behövde köra servern som production mode.
