### ISSUE TITLE
Ingen användarhantering

### ISSUE THREAD

**Issue by WheresMarco** [fjohansson92/1DV450_fj222dr#10]
Vad jag kan se i API:et så finns det ingen användarhantering förutom att skapa upp en API-nyckel. Som jag läser kriterierna så ska det finnas ett sätt att skapa upp användare som sedan skapar restauranger/taggar. 

Är det omniauth som ska hantera det här (som jag hittar i koden)? Jag kan skapa restauranger utan att logga in mig via det - och jag hittar inget klart sätt hur man gör det.

**Comment by fjohansson92** [comment]
Anledningen till att det fungerar är att jag har lagt in auth-token och user-token i Postman och i seed filen.
Omniauth var i test mode. Hämta min senaste publicering.
Gjorde en test applikation så du kan prova.  
I filen 'LoginTester/index.html' får du ändra callback url:en till något lämpligt.
Sen får du starta en XAMPP server eller liknande och gå till 'LoginTester/index.html'.
Då ska du redirectas till Github och logga in sen ska du komma till 'LoginTester/loggedinhtml' där du får upp giltliga värden för auth-token och user-token.
Får du felet 'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed' kan du lösa det enkelt såhär: https://gist.github.com/fnichol/867550
Skulle kanske haft med detta från början, skriv om något är oklart.
