### ISSUE TITLE
Jh222vp utvärdering Registreringsapplikation

### ISSUE THREAD

**Issue by jh222vp** [fjohansson92/1DV450_fj222dr#2]
Hej,

Nu fick jag igång applikationen och den verkar fungerar som den ska och följer kraven.

Lite saker jag upptäckte var följande:

Modifierar man adressfältet och ändrar sökvägarna så hamnar man på en "röd-ful" felsida som talar om för mig att det inte gick att routa mitt anrop till något som matchar det jag sökte efter. Detta kanske kunde lösas genom att man routar om "ful-sidorna" till en egengjord sådan som också kanske kan innehålla en tillbaka-knapp. Man hamnar också vid en felsida när om man försöker komma åt någon annans konto-id genom att modifiera adressfältet. Detta kunde man kanske löst genom att routa tillbaka användaren till den användare som är inloggad eller login-sidan.

Vid skapandet av API-nyckeln så kunde det varit trevligt med ett exempel på hur man ska skriva in sin sökväg till till domänen. Inte glasklart att man behöver ha http/https som prefix och att då ha ett exempel på hur denna ska se ut hade varit ett plus!

Sammanfattning
Jag tycker att du gjort en schysst sida och den gör jobbet bra. Snygg design och mycket funktioner. Det jag har påpekat ovan kan du säkerligen lätt fixa till då de är småsaker och jag tycker din applikation är godkänd! Bra jobbat!

**Comment by fjohansson92** [comment]
Det med felsidorna hade jag tänkt göra men glömde helt bort det, så det ska jag fixa.
Bra det med domänen, sånt som blir sjävklart för en själv. Ska lägga in lite instruktioner.

Tack för feedback och komplimanger!
