### ISSUE TITLE
Installations instruktioner

### ISSUE THREAD

**Issue by afrxx09** [fjohansson92/1DV450_fj222dr#3]
Ingen stor grej men tänkte endå nämna det.
Man måste köra bundle install först.

Vissa kan ha problem med bundle install och ssl. Då kan man ändra sin "source" längst upp i gem-filen från:
source 'https://rubygems.org'
till
source 'http://rubygems.org'
Sånt kan vara värt att nämna i sina instruktioner.

Annars gick installationen bra.

**Comment by fjohansson92** [comment]
Japp nämnde att jag glömt skriva det i första issuen.
