### ISSUE TITLE
Användare kan inte ta bort sitt konto

### ISSUE THREAD

**Issue by afrxx09** [fjohansson92/1DV450_fj222dr#4]
När man är inloggad som vanlig användare och kollar sitt konto så presenteras möjligheten att ta bort sitt konto, men detta fungerar inte då "destroy" i "UserController" endast får exekveras av admin.

Jag tror du löser det genom att endast lägga till ":destroy" på "before_action :correct_user" i UserController.

**Comment by fjohansson92** [comment]
Tror jag hade tänkt att man inte skulle kunna ta bort sitt konto men då skulle ju inte länken vara där. Men kan ju vara bra att kunna göra det så gör nog som du föreslog. Bra upptäckt!
