### ISSUE TITLE
Användare: UI och navigering

### ISSUE THREAD

**Issue by afrxx09** [fjohansson92/1DV450_fj222dr#5]
Som inloggad användare känns det generellt som det är många klick och sidladdningar som behövs för att utföra någonting. Skulle kanske kunna slimma ner lite här.
Sidan konto innehåller bara 3 länkar, varav en inte fungerar ( #4 ), en länk till API-nycklar som är samma som den uppe i menyn. Ett förslag skulle vara att bara ha en sida för "konto" där både användarens information finns och kan redigeras samt alla nycklar det kontot finns i en lista.

Sidan "show" för en nyckel känns också överflödig, här skulle du kunna ha två länkar/knappar till redigera/ta bort direkt i listan över nycklar. Dessutom "redigera nyckel" verkar innebära "redigera domän". Dessutom krävs det "http://" eller "https://" vilket inte framkommer helt tydligt.

**Comment by fjohansson92** [comment]
Håller med om att det blir lite onödiga sidor. Kanske slår ihop konto och API sidan. "Show" sidan för en nyckel hade jag dock en tanke med då jag tror det kommer tillkomma lite data om nyckelm, antal anropp och sånt.
