### ISSUE TITLE
Allmän utvärdering

### ISSUE THREAD

**Issue by afrxx09** [fjohansson92/1DV450_fj222dr#6]
Tycker applikationen är bra, koden är väl strukturerad och det känns som säkerhet finns i åtanke överallt. Gillar att nycklarna är kopplade mot en domän, hade gärna sett att det var en "en-till-många" relation mellan api-nyckel och domän så den kan fungera på flera domäner än en.

Hade som sagt gärna sett att interfacet var lite mer "slimmat" (issue #5 ). Man måste navigera runt lite väl mycket mellan olika sidor, detta hade lätt kunnat lösas på en enda sida. En sida med användaruppgifterna som kan redigeras och alla nycklarna med länkar direkt till redigera/ta bort utan att behöva gå in på varje nyckel för att göra det.

Men som sagt, över lag ett bra jobb.

**Comment by fjohansson92** [comment]
Tack för utvärderingen! Har slagit ihop konto och API-nycklar nu. 
Vad ser du för fördelar med att kunna ha nycklen till flera domäner? Jag tänker att det kan vara dumt att flera kan applikationer slutar fungera om den blir revoked.

**Comment by afrxx09** [comment]
Det kan vara bra för utvecklingen eller sub-domäner.
När man sitter och utvecklar så kanske man jobbar med "localhost" eller "127.0.0.1". och då vill man ju att det ska fungera så man kan testa ordentligt under utveckling. Man kanske har flera domäner till sin applikation eller rent av delar upp olika funktioner på olika domäner.
- http://www.asd.se
- https://www.asd.se
- http://asd.se
- https://asd.se
- http://www.asd.com
- https://www.asd.com
- http://asd.com
- https://asd.com

**Comment by fjohansson92** [comment]
Tänkte inte på det. Har fixat det nu. Prova gärna om du orkar!

**Comment by 1dv450** [comment]
Bra feedback och kommetarer! :+1:
