### ISSUE TITLE
Kan inte få igång appen

### ISSUE THREAD

**Issue by WheresMarco** [fjohansson92/1DV450_fj222dr#8]
Stöter på flera problem när jag försöker få igång ditt API. Jag använder http://nitrous.io och har lagt till Redis med hjälp av guiden på http://help.nitrous.io/redis/. Jag måste starta upp servern med `rails s -b 0.0.0.0` och starta Redis separat.

Men när jag startar upp servern får jag följande fel:
![skarmavbild 2015-03-04 kl 14 51 30](https://cloud.githubusercontent.com/assets/521132/6484656/f6aa9d72-c27d-11e4-89e7-00c52382cf6f.png)

Försöker jag köra testerna med rake test får jag detta fel:

```
action@zippy-rottweiler-100-201795:~/workspace/1DV450_fj222dr/registration$ rake test                                                                                                                            
rake aborted!                                                                                                                                                                                                    
NameError: uninitialized constant Api::V1                                                                                                                                                                        
/home/action/workspace/1DV450_fj222dr/registration/test/controllers/api/v1/apikeys_controller_test.rb:3:in `<top (required)>'                                                                                    
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'                                                                                        
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `each'                                                                                                              
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'                                                                                        
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:113:in `each'                                                                                                              
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'                                                                                                   
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'                                                                                                   
/home/action/.gem/ruby/2.1.1/gems/railties-4.2.0/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'                                                                                               
Tasks: TOP => test:run                                                                                                                                                                                           
(See full trace by running task with --trace)    
```

**Comment by fjohansson92** [comment]
Jadu. Aldrig använt nitrous, kan du tänka dig att köra en WEBrick server som jag föreslog?

**Comment by WheresMarco** [comment]
Nitrous är en precis som en virtuell maskin, så jag kör exakt samma rails installation som om jag skulle installerat det på datorn. WEBrick används som server där.

Jag får försöka igen ikväll med en virtuell maskin på min lokala dator och se om det fungerar där istället.

**Comment by fjohansson92** [comment]
Okej hör av dig om det inte går.

**Comment by WheresMarco** [comment]
Fick igång den efter att ha installerat allt möjligt på min dator. Dock får jag routes-fel när jag försöker använda API:et.

![skarmavbild 2015-03-05 kl 08 51 18](https://cloud.githubusercontent.com/assets/521132/6501128/d10cb2f2-c314-11e4-896e-daaa5903f935.png)

**Comment by WheresMarco** [comment]
Efter jag hittade att du använder en subdomän, vilket min lokala installation inte alls gillar, och har kommenterat bort den så fick jag API:et att fungera :+1:

**Comment by fjohansson92** [comment]
Använder du http://api.lvh.me:3001 ?

**Comment by WheresMarco** [comment]
Testade med http://api.localhost:3000 men det gick inte. Men kommenterade jag bort api-constrainten så fungerade det med http://localhost:3000 istället.

**Comment by fjohansson92** [comment]
Localhost stödjer inte subdomains, lvh.me motsvarar också 127.0.0.1

**Comment by WheresMarco** [comment]
Aha, konstigt att det inte fungerade för mig att surfa in på den adressen när jag körde igång servern. Har du ändrat i din hosts-fil för att få det fungera?

**Comment by fjohansson92** [comment]
Nej. Om du bara går in på http://lvh.me:3000 kommer du till registreringssidan då?

**Comment by WheresMarco** [comment]
Skumt, nu fungerade det. Med subdomänen också.
